#jinja2:  variable_start_string: "[%" , variable_end_string: "%]"
---

- hosts: 127.0.0.1
  connection: local
  tasks:

    - name: Update the list of available packages (= apt-get update)
      apt: update_cache=yes
    - name: Upgrade all packages
      apt: upgrade=dist

    - name: Install basic software
      apt: name={{ item }} state=present
      with_items:
        - chromium-browser 
        - gnome-shell
        - blender
        - preload
        - vim
        - gimp
        - libreoffice
        - vlc
	- ffmpeg
        - imagemagick
        - tmux
        - irssi
        - audacity
	- git

