---

- hosts: 127.0.0.1
  connection: local
  tasks:

    - name: Update the list of available packages (= apt-get update)
      apt: update_cache=yes
    - name: Upgrade all packages
      apt: upgrade=dist

    - name: Install basic software
      apt: name={{ item }} state=present
      with_items:
        - chromium-browser 
        - gnome-shell
        - blender
        - preload
        - vim
        - gimp
        - libreoffice
        - vlc
        - libav-tools
        - imagemagick
        - tmux
        - irssi
        - audacity
        - git
        - python
        - nodejs
        - npm

    - name: Copy includes for ~/.bashrc
      copy: src=files/.bash_aliases dest=~/.bash_aliases

    - name: Copy nice ~/.vimrc 
      copy: src=files/.vimrc dest=~/.vimrc
